# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2ywyQrPnsvEr6OUXIQFGo-S-dvqznyc
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller

start_date = '2020-01-01'
end_date = '2024-01-01'
tickers = ['KO', 'PEP']
data = yf.download(tickers, start=start_date, end=end_date)['Close'] # Changed 'Adj Close' to 'Close'

x = data['PEP']
y = data['KO']
x_const = sm.add_constant(x)
model = sm.OLS(y, x_const).fit()
hedge_ratio = model.params['PEP']

spread = data['KO'] - hedge_ratio * data['PEP']

window = 30
spread_mean = spread.rolling(window=window).mean()
spread_std = spread.rolling(window=window).std()
z_score = (spread - spread_mean) / spread_std

entry_threshold = 2.0
exit_threshold = 0.0

positions = pd.DataFrame(index=z_score.index)
positions['KO'] = 0
positions['PEP'] = 0

long_spread = z_score < -entry_threshold
short_spread = z_score > entry_threshold
exit_spread = abs(z_score) < 0.5

positions['signal'] = np.select(
    [long_spread, short_spread],
    [1, -1],
    default=0
)

positions['signal'] = positions['signal'].replace(0, np.nan).ffill().fillna(0)

daily_returns = data.pct_change()

strategy_returns = positions['signal'].shift(1) * (daily_returns['KO'] - hedge_ratio * daily_returns['PEP'])

plt.figure(figsize=(12, 6))
plt.title("Z-Score of KO/PEP Spread")
z_score.plot(label='Z-Score')
plt.axhline(entry_threshold, color='r', linestyle='--', label='Sell Threshold')
plt.axhline(-entry_threshold, color='g', linestyle='--', label='Buy Threshold')
plt.axhline(0, color='black', linestyle='-', label='Mean')
plt.legend()
plt.show()

cumulative_strategy_returns = (1 + strategy_returns).cumprod()
cumulative_ko_returns = (1 + daily_returns['KO']).cumprod()

plt.figure(figsize=(12, 6))
plt.title("Cumulative Returns: Strategy vs Holding KO")
cumulative_strategy_returns.plot(label='Pairs Trading Strategy', color='blue')
cumulative_ko_returns.plot(label='Buy & Hold KO', color='gray', alpha=0.5)
plt.legend()
plt.show()

sharpe_ratio = strategy_returns.mean() / strategy_returns.std() * np.sqrt(252)
print(f"Strategy Sharpe Ratio: {sharpe_ratio:.2f}")
print(f"Hedge Ratio: {hedge_ratio:.4f}")



